# Generated by Django 3.1.7 on 2021-03-04 14:36

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_page', models.CharField(default=None, max_length=50, verbose_name='Keyword')),
                ('description_page', models.CharField(default=None, max_length=50, verbose_name='Description')),
                ('title_tag', models.CharField(default=None, max_length=50, verbose_name='title_tag')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Заголовок главной страницы')),
                ('first_img', django_resized.forms.ResizedImageField(blank=True, crop=['right', 'top'], default=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1280, 860], upload_to='media')),
                ('second_img', django_resized.forms.ResizedImageField(blank=True, crop=['right', 'top'], default=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1280, 860], upload_to='media')),
                ('third_img', django_resized.forms.ResizedImageField(blank=True, crop=['right', 'top'], default=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1280, 860], upload_to='media')),
                ('fourth_img', django_resized.forms.ResizedImageField(blank=True, crop=['right', 'top'], default=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1280, 860], upload_to='media')),
                ('latitude', models.CharField(default=None, max_length=20, verbose_name='Широта')),
                ('longitude', models.CharField(default=None, max_length=20, verbose_name='Долгота')),
                ('text', models.TextField(default=None, max_length=500, verbose_name='Текст под слайдером')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_page', models.CharField(default=None, max_length=50, verbose_name='Keyword')),
                ('description_page', models.CharField(default=None, max_length=50, verbose_name='Description')),
                ('title_tag', models.CharField(default=None, max_length=50, verbose_name='title_tag')),
            ],
        ),
    ]
