# Generated by Django 3.1.7 on 2021-03-06 16:04

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_page', models.CharField(blank=True, default=None, max_length=50, verbose_name='Keyword')),
                ('description_page', models.CharField(blank=True, default=None, max_length=50, verbose_name='Description')),
                ('title_tag', models.CharField(blank=True, default=None, max_length=50, verbose_name='title_tag')),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Заголовок главной страницы')),
                ('first_img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[1280, 860], upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Можно загрузить только формат jpeg')], verbose_name='Первое изображение слайдера')),
                ('second_img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[1280, 860], upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Можно загрузить только формат jpeg')], verbose_name='Второе изображение слайдера')),
                ('third_img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[1280, 860], upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Можно загрузить только формат jpeg')], verbose_name='Третье изображение слайдера')),
                ('fourth_img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[1280, 860], upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Можно загрузить только формат jpeg')], verbose_name='Четвертое изображение слайдера')),
                ('latitude', models.CharField(blank=True, default=None, max_length=20, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, default=None, max_length=20, verbose_name='Долгота')),
                ('text', models.TextField(blank=True, default=None, max_length=500, verbose_name='Текст под слайдером')),
            ],
        ),
    ]
