# Generated by Django 3.1.7 on 2021-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210307_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Домашняя страница', 'verbose_name_plural': 'Домашняя страница'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description_page',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='keywords_page',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_tag',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Тэг'),
        ),
    ]
