# Generated by Django 3.1.7 on 2021-03-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210307_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Домашнюю страницу', 'verbose_name_plural': 'Домашняя страница'},
        ),
    ]
