# Generated by Django 3.1.7 on 2021-03-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210307_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Домашняя страница', 'verbose_name_plural': 'Домашняя страница'},
        ),
    ]
