# Generated by Django 3.1.7 on 2021-03-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210305_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPage',
        ),
    ]
