# Generated by Django 3.1.7 on 2021-03-06 12:12

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210306_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='description_page',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='first_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[1280, 860], upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Можно загрузить только формат jpeg')], verbose_name='Первое изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='fourth_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[1280, 860], upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Можно загрузить только формат jpeg')], verbose_name='Четвертое изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='keywords_page',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='latitude',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='longitude',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='second_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[1280, 860], upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Можно загрузить только формат jpeg')], verbose_name='Второе изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text',
            field=models.TextField(default=None, max_length=500, null=True, verbose_name='Текст под слайдером'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='third_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[1280, 860], upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Можно загрузить только формат jpeg')], verbose_name='Третье изображение слайдера'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_tag',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='title_tag'),
        ),
    ]
