# Generated by Django 3.1.7 on 2021-03-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210306_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='description_page',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='keywords_page',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='latitude',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='longitude',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=500, verbose_name='Текст под слайдером'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_tag',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='title_tag'),
        ),
    ]
