# Generated by Django 3.1.7 on 2021-03-06 11:49

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_page', models.CharField(default=None, max_length=50, verbose_name='Keyword')),
                ('description_page', models.CharField(default=None, max_length=50, verbose_name='Description')),
                ('title_tag', models.CharField(default=None, max_length=50, verbose_name='title_tag')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='URL')),
                ('img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[1280, 1024], upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Можно загрузить только формат jpeg')])),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(default=None, max_length=50, null=True, verbose_name='Заголовок1')),
                ('title2', models.CharField(default=None, max_length=50, null=True, verbose_name='Заголовок2')),
                ('title3', models.CharField(default=None, max_length=50, null=True, verbose_name='Заголовок3')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_num', models.CharField(choices=[('1', 'Для первого заголовка'), ('2', 'Для второго заголовка'), ('3', 'Для третьего заголовка')], max_length=1)),
                ('text', models.TextField(max_length=100)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
