# Generated by Django 3.1.7 on 2021-03-04 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('img', django_resized.forms.ResizedImageField(blank=True, crop=['right', 'top'], default=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1280, 1024], upload_to='media')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(default=None, max_length=50, verbose_name='Заголовок1')),
                ('title2', models.CharField(default=None, max_length=50, verbose_name='Заголовок2')),
                ('title3', models.CharField(default=None, max_length=50, verbose_name='Заголовок3')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
