# Generated by Django 3.1.7 on 2021-03-04 14:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'left'], default=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1280, 1024], upload_to='media'),
        ),
    ]
