# Generated by Django 3.1.7 on 2021-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210306_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description_page',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='keywords_page',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Заголовок1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_tag',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='title_tag'),
        ),
    ]
