# Generated by Django 3.1.7 on 2021-03-04 15:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210304_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[1280, 1024], upload_to='media'),
        ),
    ]
