# Generated by Django 3.1.7 on 2021-03-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_page',
            field=models.CharField(default=None, max_length=50, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords_page',
            field=models.CharField(default=None, max_length=50, verbose_name='Keyword'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_tag',
            field=models.CharField(default=None, max_length=50, verbose_name='title_tag'),
        ),
    ]
